### PR TITLE
ussf: Add version 1.5.0.0

### PR DESCRIPTION
**Pull request by h404bi**
License: Apache-2.0

A really useful utility to detect software installer file type. But the original download appears to be inactive. I will make a manifest for this tool and submit it to the extras bucket.

https://www.softpedia.com/get/System/Launchers-Shutdown-Tools/Universal-Silent-Switch-Finder.shtml

### CODE REVIEW

**Comment by r15ch13** [comment]
Found the Source :grin:
https://github.com/alexandruavadanii/USSF

**Comment by h404bi** [comment]
Nice catch! What a old software.

**Comment by h404bi** [comment]
Is it necessary? The software doesn't have updates for a long time.

**Comment by Ash258** [comment]
My main reason is consistency.

But on other hand someone could fork it and releae a new version which could be used.

**Comment by h404bi** [comment]
@r15ch13 https://github.com/lukesampson/scoop-extras/pull/2133 😃

**Pull request merged**
