### PR TITLE
cheat-engine: Add version 7.5

### PR DESCRIPTION
**Pull request by daailouivan**

### CODE REVIEW

**Comment by rashil2000** [comment]
> Remove annoying laugh and window re-sizer on ce 7.5 when choosing not to install the malware packed into the official installer.

There's malware packed into the official installer?

**Comment by Calinou** [comment]
> There's malware packed into the official installer?

Yes, Cheat Engine is notorious for doing stuff like this for at least a few years now.

**Review by rashil2000 — APPROVED** [review]

**Comment by leumasme** [comment]
Image of what they are talking about:
image
This fork uses github actions to automatically pull changes from the CheatEngine repo and build them: https://github.com/ardittristan/cheat-engine

**Comment by rashil2000** [comment]
> This fork uses github actions to automatically pull changes from the CheatEngine repo and build them to create clean builds: https://github.com/ardittristan/cheat-engine

Oh, interesting! We should use this as a source of the builds then.

**Pull request closed without merging**
