### PR TITLE
innounp: Add version 0.4.9

### PR DESCRIPTION
**Pull request by niheaven**
Added support for IS 6.0.

https://www.virustotal.com/#/file/4a636ff9213928a919717d0fab28e525fb992d9bb5f2d4a9ab2fd97132690741/detection

### CODE REVIEW

**Comment by brandon93s** [comment]
@r15ch13 - Can I have write access to this repo so that I may merge?

**Comment by rasa** [comment]
@r15ch13 Me too, if only to help with triaging, et al.

**Comment by niheaven** [comment]
So could `Binary` be added to`Buckets Maintainer` group?

**Comment by r15ch13** [comment]
Added maintainer group :)

**Pull request merged**
